#!/bin/bash
if [ ! -d .git ]; then
	git init
	git remote add origin https://github.com/nshattuck20/cs143_project.git
	git remote add upstream https://github.com/rgschmitz1/cs143_project.git
fi
git pull upstream master
